# Generated by Django 3.0.5 on 2020-05-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitement', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcool', models.BooleanField(default=False)),
                ('drogue', models.BooleanField(default=False)),
                ('tabac', models.BooleanField(default=False)),
                ('Maladie', models.CharField(blank=True, max_length=12)),
                ('antecedant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Antecedent')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient')),
                ('traitement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Traitement')),
            ],
        ),
    ]
