# Generated by Django 3.0.5 on 2020-05-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitudeToxique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcool', models.BooleanField(default=False)),
                ('drogue', models.BooleanField(default=False)),
                ('tabac', models.BooleanField(default=False)),
            ],
        ),
    ]
