# Generated by Django 3.0.5 on 2020-06-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anesthesiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Chirurgien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcool', models.BooleanField(default=False)),
                ('drogue', models.BooleanField(default=False)),
                ('tabac', models.BooleanField(default=False)),
                ('maladie', models.CharField(blank=True, max_length=12)),
                ('numero', models.CharField(blank=True, max_length=12)),
                ('TDM', models.BooleanField(default=False)),
                ('IRM', models.BooleanField(default=False)),
                ('RADIO', models.BooleanField(default=False)),
                ('ECHO', models.BooleanField(default=False)),
                ('espaceClinique', models.CharField(blank=True, max_length=300)),
                ('avisMedical', models.CharField(blank=True, max_length=300)),
                ('ordonnance', models.CharField(blank=True, max_length=300)),
                ('dateDebutCertificat', models.DateField(blank=True, null=True)),
                ('descriptionCertificat', models.CharField(blank=True, max_length=300)),
                ('dateFinCertificat', models.DateField(blank=True, null=True)),
                ('nbrJour', models.IntegerField(blank=True, null=True)),
                ('tdms', models.ImageField(blank=True, default='s.jpg', null=True, upload_to='tdm/')),
                ('irms', models.ImageField(blank=True, default='s.jpg', null=True, upload_to='irm/')),
                ('radios', models.ImageField(blank=True, default='s.jpg', null=True, upload_to='radio/')),
                ('echos', models.ImageField(blank=True, default='s.jpg', null=True, upload_to='echo/')),
                ('antecedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Antecedent')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeSanguin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sang', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('grade', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('specialite', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuriteSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitement', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=128, null=True)),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('ville', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='')),
                ('chirurgien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chirurgien', to='medicalStaff.Chirurgien')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to='medicalStaff.Medecin')),
                ('securiteSocial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SR', to='medicalStaff.SecuriteSocial')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIntervention', models.DateField(blank=True, null=True)),
                ('heureIntervention', models.TimeField(blank=True, null=True)),
                ('dureeIntervention', models.CharField(max_length=50)),
                ('lieuIntervention', models.CharField(max_length=50, null=True)),
                ('typeIntervention', models.CharField(choices=[('Première', 'Première'), ('Retouche', 'Retouche'), ('Reprise', 'Reprise')], max_length=50, null=True)),
                ('modeIntervention', models.CharField(choices=[('Programmée', 'Programmée'), ('urgente', 'urgente')], max_length=50, null=True)),
                ('anesthesie', models.CharField(choices=[('Loale', 'Locale'), ('Générale', 'Générale')], max_length=50, null=True)),
                ('compteRendu', models.FileField(null=True, upload_to='compte-rendu/')),
                ('resultat', models.CharField(choices=[('Satisfaction', 'Satisfaction'), ('Insuffisance', 'Insuffisance'), ('Echec', 'Echec'), ('Décés', 'Décés')], max_length=50, null=True)),
                ('technique', models.CharField(max_length=50, null=True)),
                ('complication', models.CharField(max_length=500, null=True)),
                ('anesthesiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Anesthesiste')),
                ('chirurgien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Chirurgien')),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Infirmier')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Medecin')),
                ('numero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(choices=[('Urgente', 'Urgente'), ('Réadmission', 'Réadmission'), ('Précoce', 'Précoce'), ('Réglée', 'Réglée')], max_length=50, null=True)),
                ('lit', models.IntegerField(default=0)),
                ('dateSortie', models.DateField(blank=True, null=True)),
                ('numero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Consultation')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='groupeSanguin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.GroupeSanguin'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='traitement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Traitement'),
        ),
    ]
