# Generated by Django 3.0.5 on 2020-05-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anesthesiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Chirurgien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeSanguin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sang', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('grade', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('specialite', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuriteSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitement', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=128, null=True)),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('ville', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('chirurgien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chirurgien', to='medicalStaff.Chirurgien')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to='medicalStaff.Medecin')),
                ('securiteSocial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SR', to='medicalStaff.SecuriteSocial')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcool', models.BooleanField(default=False)),
                ('drogue', models.BooleanField(default=False)),
                ('tabac', models.BooleanField(default=False)),
                ('Maladie', models.CharField(blank=True, max_length=12)),
                ('numero', models.CharField(blank=True, max_length=12)),
                ('TDM', models.BooleanField(default=False)),
                ('IRM', models.BooleanField(default=False)),
                ('RADIO', models.BooleanField(default=False)),
                ('ECHO', models.BooleanField(default=False)),
                ('antecedant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Antecedent')),
                ('groupeSanguin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.GroupeSanguin')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Patient')),
                ('traitement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Traitement')),
            ],
        ),
    ]
