# Generated by Django 3.0.5 on 2020-05-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chirurgien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SecuriteSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=128, null=True)),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('chirurgien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chirurgien', to='medicalStaff.Chirurgien')),
                ('dossier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.DossierMedical')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to='medicalStaff.Medecin')),
                ('securiteSocial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SR', to='medicalStaff.SecuriteSocial')),
            ],
        ),
    ]
