# Generated by Django 3.0.5 on 2020-05-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='espaceClinique',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
