# Generated by Django 3.0.5 on 2020-06-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='antecedent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Antecedent'),
        ),
    ]
