# Generated by Django 3.0.5 on 2020-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0002_patient_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
