# Generated by Django 3.0.5 on 2020-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0003_dossiermedical_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('grade', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
