# Generated by Django 3.0.5 on 2020-05-19 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0004_auto_20200512_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIntervention', models.DateField(blank=True, null=True)),
                ('heureIntervention', models.TimeField(blank=True, null=True)),
                ('dureeIntervention', models.CharField(max_length=50)),
                ('lieuIntervention', models.CharField(max_length=50, null=True)),
                ('typeIntervention', models.CharField(choices=[('Première', 'Première'), ('Retouche', 'Retouche'), ('Reprise', 'Reprise')], max_length=50, null=True)),
                ('modeIntervention', models.CharField(choices=[('Programmée', 'Programmée'), ('urgente', 'urgente')], max_length=50, null=True)),
                ('anesthesie', models.CharField(choices=[('Loale', 'Locale'), ('Générale', 'Générale')], max_length=50, null=True)),
                ('compteRendu', models.FileField(null=True, upload_to='compte-rendu/')),
                ('resultat', models.CharField(choices=[('Satisfaction', 'Satisfaction'), ('Insuffisance', 'Insuffisance'), ('Echec', 'Echec'), ('Décés', 'Décés')], max_length=50, null=True)),
                ('technique', models.CharField(max_length=50, null=True)),
                ('complication', models.CharField(max_length=500, null=True)),
                ('anesthesiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Anesthesiste')),
                ('chirurgien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Chirurgien')),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Infirmier')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Medecin')),
                ('numero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(choices=[('Urgente', 'Urgente'), ('Réadmission', 'Réadmission'), ('Précoce', 'Précoce'), ('Réglée', 'Réglée')], max_length=50, null=True)),
                ('lit', models.IntegerField(default=0)),
                ('dateSortie', models.DateField(blank=True, null=True)),
                ('numero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalStaff.Consultation')),
            ],
        ),
    ]
