# Generated by Django 3.0.5 on 2020-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0004_infirmier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infirmier',
            name='numero',
        ),
        migrations.AddField(
            model_name='infirmier',
            name='prénom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
