# Generated by Django 3.0.5 on 2020-05-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0005_auto_20200508_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infirmier',
            old_name='prénom',
            new_name='prenom',
        ),
    ]
