# Generated by Django 3.0.5 on 2020-05-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0006_auto_20200508_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infirmier',
            old_name='nom',
            new_name='nom_inf',
        ),
        migrations.RenameField(
            model_name='infirmier',
            old_name='prenom',
            new_name='prenom_inf',
        ),
    ]
