# Generated by Django 3.0.5 on 2020-05-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0007_auto_20200508_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infirmier',
            old_name='nom_inf',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='infirmier',
            old_name='prenom_inf',
            new_name='prenom',
        ),
    ]
