# Generated by Django 3.0.5 on 2020-05-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStaff', '0009_auto_20200509_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirurgien',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chirurgien',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
